### ISSUE TITLE
Cannot Resolve

### ISSUE THREAD

**Issue by BryanARivera** [tototoshi/play-scalate#2]
Simply including play-scalate does not work.  

Where are your releases?  Can't find it on GH or MVN.

**Comment by futurehorizon** [comment]
I checked your SBT file and found its at Sonatype.

Please add:

```
  resolvers += Resolver.sonatypeRepo("public"),
```

to your how to.

**Comment by futurehorizon** [comment]
The 0.1.0 snapshot is available but 0.2.0 is not.

**Comment by tototoshi** [comment]
Published 0.2.0
